import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import RootProvider from '@/contexts/root'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import 'react-date-picker/dist/DatePicker.css'
import 'react-calendar/dist/Calendar.css'
import AccountProvider from '@/contexts/account'
import { cookies } from 'next/headers'
import 'swiper/css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'DKEducation',
  description:
    'Skills for your present (and your future). Get started with us.Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const cookieStore = cookies()
  const accessToken = cookieStore.get('accessToken')?.value as string
  const refreshToken = cookieStore.get('refreshToken')?.value as string
  const tokens = { accessToken, refreshToken }
  return (
    <html lang="en" className="dark" suppressHydrationWarning={false}>
      <body className={`${inter.className} bg-background`}>
        <RootProvider>
          <AccountProvider inititalTokens={tokens}>
            <ToastContainer theme="dark" />
            {children}
          </AccountProvider>
        </RootProvider>
      </body>
    </html>
  )
}
