import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/layouts/Header'
import RootProvider from '@/contexts/root'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'DK Education',
  description:
    'Skills for your present (and your future). Get started with us.Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${inter.className} bg-background`}>
        <RootProvider>
          <ToastContainer theme="dark" />
          <Header />
          {children}
        </RootProvider>
      </body>
    </html>
  )
}
